### ISSUE TITLE
Ultra stamp guide 

### ISSUE THREAD

**Issue by StampMan123** [wellstring/guides#1]
I made a ultra stamp guide ~7 months ago, so it's a bit outdated for the likes of well string and decav, but I think it still holds up well. 

https://youtu.be/5qfHsZwmq5M?si=HdhBUTOOYO0jmvcR

**Comment by wellstring** [comment]
Having watched a bit of the video, it tends to be more gameplay focused than I'd like for a guide listed here to be. This can obviously still be helpful, but it can make referencing the video for information difficult.
